import test from 'node:test';import assert from 'node:assert/strict';import {harness,loadImage} from './qa-harness.mjs';
import {sourceCrop} from '../web/source-cleanup.mjs';import {labelsFromTSV} from '../web/editor-core.mjs';
const box={x:298,y:277,w:105,h:29};
test('empty instruction: no edits and no AI request',async()=>{const h=harness(),p=h.pixels();await h.submit('  ');assert.equal(h.calls(),0);assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,0);});
test('busy submission: no duplicate edits',async()=>{const h=harness();h.c.qa.busy(true);await h.submit('rename living to lounge');assert.equal(h.get().history.length,0);assert.equal(h.calls(),0);});
test('longer label: same font, colour, centre and measurement pixels',async()=>{const h=harness(),r=h.canvas.getContext('2d').getImageData(280,309,180,25).data;h.select(box);await h.submit("relabel as 'formal living'");const l=h.get().labels[0];assert.equal(l.fontSize,20);assert.equal(l.color,'#333');assert.equal(l.x+l.w/2,350);assert.deepEqual(h.canvas.getContext('2d').getImageData(280,309,180,25).data,r);});
test('measurement replacement keeps its own style and position',async()=>{const h=harness();h.select({x:295,y:307,w:125,h:30});await h.submit('change measurements to 8.0 x 4.0 m');const l=h.get().labels.find(l=>l.id==='size');assert.equal(l.text,'8.0 x 4.0 m');assert.equal(l.fontSize,18);assert.equal(l.x+l.w/2,355);assert.equal(l.y,310);});
test('shorter subsequent label removes the old longer label exactly through undo/redo',async()=>{const h=harness();await h.submit('rename living to formal living');const a=h.pixels();await h.submit('rename formal living to den');const b=h.pixels();h.el('undo').onclick();assert.deepEqual(h.pixels(),a);h.el('redo').onclick();assert.deepEqual(h.pixels(),b);});
test('new text uses the selected blank area; Clear preserves selection and drawing',async()=>{const h=harness();h.select({x:100,y:450,w:130,h:30});const before=h.pixels();h.el('instruction').value='test';h.el('clearinstruction').onclick();assert.equal(h.el('instruction').value,'');assert(h.get().manual);assert.deepEqual(h.pixels(),before);await h.submit("Add 'site plan' in small black text");assert(h.get().labels.some(l=>l.text==='site plan'));});
test('empty Undo and Redo do nothing',()=>{const h=harness(),p=h.pixels();h.el('undo').onclick();h.el('redo').onclick();assert.deepEqual(h.pixels(),p);});
test('new edit after undo clears redo',async()=>{const h=harness();await h.submit('rename living to lounge');h.el('undo').onclick();await h.submit('rename living to family');assert.equal(h.get().future.length,0);});
test('failed batch restores drawing and redo history',async()=>{const h=harness();await h.submit('rename living to lounge');h.el('undo').onclick();const before=h.pixels();await h.submit('rename living to family and add a car in the driveway');assert.deepEqual(h.pixels(),before);assert.equal(h.get().future.length,1);h.el('redo').onclick();assert.equal(h.get().labels[0].text,'lounge');});
for(const kind of ['bbq','car','toilet','sink','bath','shower'])test('selected '+kind+' insertion and undo',async()=>{const h=harness(),p=h.pixels();h.select({x:100,y:400,w:160,h:170});await h.submit('add a '+kind);assert.equal(h.get().history.length,1);assert.notDeepEqual(h.pixels(),p);h.el('undo').onclick();assert.deepEqual(h.pixels(),p);});
test('tiny fixture selection rejects without change',async()=>{const h=harness(),p=h.pixels();h.select({x:100,y:100,w:5,h:5});await h.submit('add a car');assert.equal(h.get().history.length,0);assert.deepEqual(h.pixels(),p);});
test('footer edits reject without change',async()=>{const h=harness(),p=h.pixels();h.select({x:50,y:680,w:200,h:15});await h.submit("add 'footer' in small black text");assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,0);});
test('duplicate room names require a selection',async()=>{const h=harness();h.c.qa.seed([{id:'a',text:'GARDEN',x:100,y:100,w:100,h:25,fontSize:20},{id:'b',text:'GARDEN',x:600,y:100,w:100,h:25,fontSize:20}]);const p=h.pixels();await h.submit('rename garden to lawn');assert.deepEqual(h.pixels(),p);h.select({x:98,y:98,w:105,h:30});await h.submit("relabel as 'lawn'");assert.equal(h.get().labels[0].text,'lawn');assert.equal(h.get().labels[1].text,'GARDEN');});
test('numeric-only OCR line remains editable',()=>{const l=labelsFromTSV('header\n5\t1\t1\t1\t1\t1\t10\t20\t90\t15\t90\t5.3 x 5.0',1000,700);assert.equal(l.length,1);});
test('upload reset clears old undo/redo and selection',async()=>{const h=harness();await h.submit('rename living to lounge');h.el('undo').onclick();h.select(box);h.c.reset();assert.equal(h.get().future.length,0);assert.equal(h.get().history.length,0);assert.equal(h.get().manual,null);});
test('Original view does not alter the saved revision',async()=>{const h=harness();await h.submit('rename living to lounge');const p=h.pixels();h.el('source').onclick();h.el('result').onclick();assert.deepEqual(h.pixels(),p);});
test('actual user JPEG: crop and A4 output dimensions',async()=>{const source=await loadImage('/Users/user/Downloads/image (3).jpg');const h=harness();h.c.qa.load(source);assert.equal(h.canvas.width,2480);assert.equal(h.canvas.height,1754);const g=h.canvas.getContext('2d');assert.equal(g.getImageData(20,800,1,1).data[0],255);assert.equal(g.getImageData(2460,800,1,1).data[0],255);});
test('relabel blank space refuses instead of inventing a font',async()=>{const h=harness(),p=h.pixels();h.select({x:100,y:100,w:100,h:25});await h.submit("relabel as 'living'");assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,0);});
test('oversized replacement cannot erase neighbouring label',async()=>{const h=harness();h.c.qa.seed([{id:'a',text:'A',x:300,y:280,w:20,h:25,fontSize:20},{id:'b',text:'BEDROOM',x:345,y:280,w:100,h:25,fontSize:20}]);const p=h.pixels();await h.submit('rename A to very long formal living room');assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,0);});
test('selected replacement covering multiple labels requires a tighter selection',async()=>{const h=harness();h.get().labels[1].text='DINING';const p=h.pixels();h.select({x:295,y:275,w:140,h:65});await h.submit("relabel as 'lounge'");assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,0);});
test('unsupported AI plan operation leaves every pixel unchanged',async()=>{const h=harness(),p=h.pixels();h.setResponse({ok:true,json:async()=>({message:'',operations:[{type:'execute',text:'',labelId:''}]})});await h.submit('make this magic');assert.deepEqual(h.pixels(),p);});
test('AI question is not a failure and can be answered in the instruction box',async()=>{const h=harness();h.setResponse({ok:true,json:async()=>({message:'Only the selected trees?',operations:[]})});await h.submit('tidy the trees');assert.equal(h.get().history.length,0);assert.equal(h.el('instruction').value,'');assert.match(h.el('status').textContent,/reply/i);});
test('replacement expansion stops before a wall',async()=>{const h=harness();h.c.qa.seed([{id:'a',text:'A',x:300,y:280,w:20,h:25,fontSize:20}]);h.c.qa.wall(345,260,8,70);const p=h.pixels();await h.submit('rename A to a very long replacement');assert.deepEqual(h.pixels(),p);});
test('overlong instruction rejects without AI',async()=>{const h=harness();await h.submit('x'.repeat(4001));assert.equal(h.calls(),0);assert.equal(h.get().history.length,0);});
test('unsupported upload type preserves the current revision',async()=>{const h=harness();await h.submit('rename living to lounge');const p=h.pixels();await h.c.upload({size:100,type:'text/plain'});assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,1);});
test('oversized upload preserves the current revision',async()=>{const h=harness();await h.submit('rename living to lounge');const p=h.pixels();await h.c.upload({size:21*1024*1024,type:'image/jpeg'});assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,1);});

test('corrupt image upload restores the drawing, history and filename',async()=>{const h=harness();await h.submit('rename living to lounge');const p=h.pixels();h.el('title').textContent='current.jpg';h.c.imageFrom=async()=>{throw Error('Corrupt image');};await h.c.upload(new Blob(['invalid'],{type:'image/jpeg'}));assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,1);assert.equal(h.el('title').textContent,'current.jpg');});
test('export from Original view uses the edited A4 drawing',async()=>{const h=harness();await h.submit('rename living to lounge');const expected=h.pixels();h.el('source').onclick();let captured;const create=h.c.document.createElement;h.c.document.createElement=t=>{const c=create(t);if(t==='canvas')c.toBlob=()=>{captured=c.toBuffer('image/png');};return c;};h.el('export').onclick();assert.deepEqual(captured,expected);});
test('clarification response is included in the next AI request',async()=>{const h=harness();let requestBody;const original=h.c.fetch;h.c.fetch=async(url,options)=>{requestBody=JSON.parse(options.body);return {ok:true,json:async()=>({message:'Only the selected trees?',operations:[]})};};await h.submit('tidy the trees');await h.submit('Only the selected trees');assert.match(requestBody.instruction,/tidy the trees/);assert.match(requestBody.instruction,/User answer: Only the selected trees/);});

test('new text overlapping an existing label rejects without erasing either',async()=>{const h=harness(),p=h.pixels();h.select(box);await h.submit("Add 'site plan' in small black text");assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,0);});
test('added caption remains pixel-identical after a later fixture',async()=>{const h=harness();h.select({x:100,y:450,w:130,h:30});await h.submit("Add 'site plan' in small black text");const pixels=h.canvas.getContext('2d').getImageData(100,450,130,30).data;assert(pixels.some((v,i)=>i%4===0&&v<100));h.select({x:650,y:400,w:160,h:170});await h.submit('add a car');assert.equal(h.get().history.length,2);assert.deepEqual(h.canvas.getContext('2d').getImageData(100,450,130,30).data,pixels);});
test('OCR font estimate reproduces the original capital height',async()=>{const {tightenLabel}=await import('../web/editor-core.mjs');const h=harness();h.c.qa.seed([{id:'a',text:'LIVING',x:300,y:280,w:100,h:25,fontSize:20}]);const g=h.canvas.getContext('2d'),l={x:298,y:277,w:105,h:29};tightenLabel(l,g.getImageData(0,0,1000,700).data,1000,700);assert(Math.abs(l.fontSize-20)<2);});
test('direct footer OCR removes a complete faint disclaimer line but preserves room text',async()=>{const h=harness();const row=(id,x,y,w,text)=>`5\t1\t1\t1\t${id}\t1\t${x}\t${y}\t${w}\t12\t80\t${text}`;await h.c.readSourceDisclaimer({recognize:async()=>({data:{tsv:'header\n'+row(1,100,200,1600,'The floor plan is not to scale; measurements are indicative and in metres.')+'\n'+row(2,300,30,300,'BEDROOM 1')}})});assert(h.get().labels.some(l=>l.id.startsWith('disclaimer-')));h.c.autoCleanup();assert(!h.get().labels.some(l=>l.id.startsWith('disclaimer-')));assert(h.get().labels.some(l=>l.text==='LIVING'));});

for(const color of ['#bbbbbb','#dedede','#ffffff'])test('icon removal matches surrounding '+color+' instead of white icon interior',async()=>{const h=harness();h.c.qa.wall(80,380,240,180,color);h.c.qa.wall(110,410,130,90,'#ffffff');h.c.qa.wall(120,420,15,60,'#222222');const before=h.pixels();h.select({x:110,y:410,w:130,h:90});await h.submit('remove selected element');assert.equal(h.get().history.length,1);const data=h.canvas.getContext('2d').getImageData(115,415,1,1).data;assert.equal(data[0],parseInt(color.slice(1,3),16));h.el('undo').onclick();assert.deepEqual(h.pixels(),before);});
test('AI text verification rejects missing, changed, moved and added words',()=>{const h=harness(),a=[{text:'bedroom',x:10,y:10},{text:'4 1 x 5 0',x:10,y:30}];assert(h.c.sameVerifiedText(a,a));assert(!h.c.sameVerifiedText(a,a.slice(0,1)));assert(!h.c.sameVerifiedText(a,[a[0],{...a[1],text:'4 7 x 5 0'}]));assert(!h.c.sameVerifiedText(a,[a[0],{...a[1],x:40}]));assert(!h.c.sameVerifiedText(a,[...a,{text:'extra',x:1,y:1}]));});
test('AI edit with unreadable baseline rejects without changing pixels or history',async()=>{const h=harness(),p=h.pixels();await assert.rejects(h.c.reviseWithImageAI('remove bed',{x:100,y:100,w:200,h:200}),/could not be verified/);assert.deepEqual(h.pixels(),p);assert.equal(h.get().history.length,0);assert.equal(h.get().busy,false);});
test('unchanged text pixels pass even if full-page OCR segmentation changes',()=>{const h=harness();const words=[{text:'living',x:300,y:280,w:100,h:25}];assert(h.c.verifyOriginalTextPixels(h.canvas,h.canvas,words,[]));});
test('erased original text fails pixel-aware verification',()=>{const h=harness();const before=h.c.flattened(),words=[{text:'living',x:300,y:280,w:100,h:25}];h.c.qa.wall(298,278,110,30,'white');assert(!h.c.verifyOriginalTextPixels(before,h.canvas,words,[]));});
test('AI-assisted BBQ resolves named placement and draws a symbol without changing other pixels',async()=>{const h=harness();h.el('aiedit').checked=true;h.setResponse({ok:true,json:async()=>({message:'',operations:[{type:'fixture',fixture:'bbq',labelId:'',text:'',rect:{x:600,y:400,w:100,h:50}}]})});const before=h.canvas.getContext('2d').getImageData(280,270,180,70).data;await h.submit('add a built-in BBQ in the covered area');assert.equal(h.get().history.length,1);assert.deepEqual(h.canvas.getContext('2d').getImageData(280,270,180,70).data,before);assert.match(h.el('status').textContent,/AI chose/);});
test('AI locator accepts multiple plant removal regions as one image editing area',async()=>{const h=harness();h.setResponse({ok:true,json:async()=>({message:'Remove two plants',operations:[{type:'remove',fixture:'',labelId:'',text:'',rect:{x:100,y:100,w:30,h:30}},{type:'remove',fixture:'',labelId:'',text:'',rect:{x:200,y:150,w:30,h:30}}]})});const r=await h.c.locateImageEdit('remove all plants');assert.equal(r.x,100);assert.equal(r.y,100);assert.equal(r.w,130);assert.equal(r.h,80);assert.equal(h.get().busy,false);});
test('pixel-aware verification rejects an invented duplicate label in changed pixels',()=>{const h=harness(),before=h.c.flattened();h.c.qa.wall(500,100,100,25,'black');const words=[{text:'living',x:300,y:280,w:100,h:25}];assert(!h.c.verifyOriginalTextPixels(before,h.canvas,words,[...words,{text:'living',x:500,y:100,w:100,h:25}]));});
test('pixel-aware verification tolerates newly recognised text only when its pixels are unchanged',()=>{const h=harness(),words=[{text:'living',x:300,y:280,w:100,h:25}];assert(h.c.verifyOriginalTextPixels(h.canvas,h.canvas,words,[...words,{text:'5 3 x 5 0 m',x:300,y:310,w:110,h:23}]));});
test('a named two-line room label joins without consuming its measurements',async()=>{const h=harness();h.c.qa.seed([{id:'main',text:'MAIN',x:305,y:260,w:50,h:22,fontSize:20},{id:'bed',text:'BEDROOM',x:280,y:285,w:100,h:22,fontSize:20},{id:'dim',text:'4.1 x 5.0m',x:280,y:315,w:110,h:22,fontSize:18}]);await h.submit('rename Main Bedroom to Study');assert.equal(h.get().history.length,1);assert(h.get().labels.some(l=>l.text==='Study'));assert(h.get().labels.some(l=>l.text==='4.1 x 5.0m'));assert(!h.get().labels.some(l=>l.text==='MAIN'));});
test('explicit text insertion stays editable when AI image editing is enabled',async()=>{const h=harness();h.el('aiedit').checked=true;h.select({x:100,y:450,w:180,h:30});await h.submit("Add 'Site Plan' in small black text");assert.equal(h.get().history.length,1);assert(h.get().labels.some(l=>l.text==='Site Plan'));assert.equal(h.calls(),0);});
test('OCR verification excludes isolated icon strokes but keeps room numbers and dimensions',async()=>{const h=harness(),row=(line,word,text)=>`5\t1\t1\t1\t${line}\t${word}\t100\t100\t20\t20\t90\t${text}`;h.c.getWorker=async()=>({recognize:async()=>({data:{tsv:'header\n'+[row(1,1,'1'),row(2,1,'BEDROOM'),row(2,2,'2'),row(3,1,'4.1'),row(3,2,'x'),row(3,3,'5.0m')].join('\n')}})});const words=await h.c.readVerificationText(h.canvas);assert.deepEqual(Array.from(words,w=>w.text),['bedroom','2','4 1','x','5 0m']);});
test('image editing restores original text pixels even when generated crop erases them',async()=>{const h=harness(),source=h.c.flattened(),words=[{text:'living',x:300,y:280,w:100,h:25},{text:'5 3 x 5 0 m',x:300,y:310,w:110,h:23}];h.c.readVerificationText=async()=>words;const generated=h.c.makeCanvas(1024,1024);generated.getContext('2d').fillStyle='white';generated.getContext('2d').fillRect(0,0,1024,1024);generated.naturalWidth=1024;h.c.imageFrom=async()=>generated;h.setResponse({ok:true,json:async()=>({image:'generated-test-image'})});await h.c.reviseWithImageAI('remove furniture',{x:250,y:250,w:220,h:150});assert.equal(h.get().history.length,1);assert.deepEqual(h.canvas.getContext('2d').getImageData(300,280,110,55).data,source.getContext('2d').getImageData(300,280,110,55).data);});
test('removal quality guard rejects a new black fill but permits dark-object removal',()=>{const h=harness(),before=h.c.flattened();h.c.qa.wall(100,400,200,100,'black');const dark=h.c.flattened(),r={x:100,y:400,w:200,h:100};assert(h.c.darkFillIntroduced(before,dark,r));assert(!h.c.darkFillIntroduced(dark,before,r));});

test('AI quality failure retries once from original and commits only the accepted result',async()=>{const h=harness();let checks=0,requests=0;h.c.readVerificationText=async()=>[{text:'living',x:300,y:280,w:100,h:25}];h.c.verifyOriginalTextPixels=()=>++checks===2;h.c.fetch=async()=>{requests++;return {ok:true,json:async()=>({image:h.canvas.toDataURL()})}};await h.c.reviseWithImageAI('remove the chair',{x:100,y:400,w:100,h:100});assert.equal(requests,2);assert.equal(h.get().history.length,1);assert.equal(h.get().busy,false);});
test('two failed AI checks keep the plan and revision history unchanged',async()=>{const h=harness(),before=h.pixels();let requests=0;h.c.readVerificationText=async()=>[{text:'living',x:300,y:280,w:100,h:25}];h.c.verifyOriginalTextPixels=()=>false;h.c.fetch=async()=>{requests++;return {ok:true,json:async()=>({image:h.canvas.toDataURL()})}};await assert.rejects(h.c.reviseWithImageAI('remove the chair',{x:100,y:400,w:100,h:100}),/after two attempts/);assert.equal(requests,2);assert.equal(h.get().history.length,0);assert.deepEqual(h.pixels(),before);assert.equal(h.get().busy,false);});

test('update to second living edits the selected label, preserves dimensions, and avoids image AI',async()=>{const h=harness();h.el('aiedit').checked=true;h.select({x:290,y:270,w:130,h:70});await h.submit('update to second living');assert.equal(h.calls(),0);assert.equal(h.get().labels[0].text,'second living');assert.equal(h.get().labels[1].text,'5.3 x 5.0 M');assert.equal(h.get().history.length,1);});

test('two selected text changes share their selection and one undo restores both',async()=>{const h=harness();h.get().labels[1].text='5.3m x 5.0m';const before=h.pixels();h.el('aiedit').checked=true;h.select({x:270,y:260,w:210,h:90});h.setResponse({ok:true,json:async()=>({message:'Mapped both changes',operations:[{type:'rename',labelId:'living',text:'second living'},{type:'rename',labelId:'size',text:'8.0 x 4.0 m'}]})});await h.submit('update to second living and update measurements to 8.0 x 4.0 m');assert.equal(h.calls(),1);assert.equal(h.get().labels[0].text,'second living');assert.equal(h.get().labels[1].text,'8.0 x 4.0 m');assert.equal(h.get().history.length,1);h.el('undo').onclick();assert.deepEqual(h.pixels(),before);h.el('redo').onclick();assert.equal(h.get().labels[1].text,'8.0 x 4.0 m');});

test('selected semantic mapping rejects labels outside the selection atomically',async()=>{const h=harness(),before=h.pixels();h.select({x:270,y:260,w:210,h:90});h.setResponse({ok:true,json:async()=>({message:'Mapped',operations:[{type:'rename',labelId:'living',text:'lounge'},{type:'rename',labelId:'outside',text:'8 x 4 m'}]})});await h.submit('call this lounge and make the size 8 x 4 m');assert.equal(h.get().history.length,0);assert.deepEqual(h.pixels(),before);});

test('portrait and colour toggles retain text edits and support undo',async()=>{const h=harness();await h.submit('rename living to lounge');h.el('colour').onclick();assert.equal(h.canvas.style.filter,'none');h.el('portrait').onclick();assert.equal(h.canvas.width,1754);assert.equal(h.canvas.height,2480);assert.equal(h.get().labels[0].text,'lounge');h.el('undo').onclick();assert.equal(h.canvas.width,1000);assert.equal(h.canvas.style.filter,'none');h.el('undo').onclick();assert.equal(h.canvas.style.filter,'grayscale(1)');assert.equal(h.get().labels[0].text,'lounge');});

for(const instruction of ['Label Bed 1','label as Bed 1','relabel Bed 1','call this Bed 1'])test('selected label wording: '+instruction,async()=>{
 const h=harness();h.el('aiedit').checked=true;h.select(box);
 const before=h.pixels(),measurements=h.canvas.getContext('2d').getImageData(280,309,180,25).data;
 await h.submit(instruction);const l=h.get().labels[0];
 assert.equal(l.text,'Bed 1');assert.equal(l.fontSize,20);assert.equal(l.color,'#333');assert.equal(l.x+l.w/2,350);
 assert.equal(h.calls(),0);assert.equal(h.get().history.length,1);
 assert.deepEqual(h.canvas.getContext('2d').getImageData(280,309,180,25).data,measurements);
 const after=h.pixels();h.el('undo').onclick();assert.deepEqual(h.pixels(),before);h.el('redo').onclick();assert.deepEqual(h.pixels(),after);
});

const bedroomSet=[{id:'b',text:'BEDROOM 8',x:600,y:100,w:100,h:25,fontSize:20,color:'#333',bg:'#fff'},{id:'a',text:'MAIN BEDROOM',x:100,y:102,w:160,h:25,fontSize:20,color:'#333',bg:'#fff'},{id:'c',text:'BED',x:100,y:400,w:80,h:25,fontSize:20,color:'#333',bg:'#fff'},{id:'d',text:'3.5 x 3.3m',x:100,y:430,w:110,h:23,fontSize:18,bg:'#fff'}];
test('number all beds uses visual order, preserves measurements and style, single undo/redo',async()=>{const h=harness();h.c.qa.seed(bedroomSet);h.el('aiedit').checked=true;const before=h.pixels();await h.submit('number all beds');assert.equal(h.calls(),0);assert.deepEqual(Array.from(h.get().labels,l=>l.text),['BED 2','BED 1','BED 3','3.5 x 3.3m']);assert.equal(h.get().labels[0].fontSize,20);assert.equal(h.get().labels[0].color,'#333');assert.equal(h.get().labels[0].x+h.get().labels[0].w/2,650);assert.equal(h.get().history.length,1);const after=h.pixels();await h.submit('number all beds');assert.equal(h.get().history.length,1);h.el('undo').onclick();assert.deepEqual(h.pixels(),before);h.el('redo').onclick();assert.deepEqual(h.pixels(),after);});
test('number bedrooms respects selection',async()=>{const h=harness();h.c.qa.seed(bedroomSet);h.select({x:80,y:380,w:200,h:80});await h.submit('number all bedrooms');assert.deepEqual(Array.from(h.get().labels,l=>l.text),['BEDROOM 8','MAIN BEDROOM','BED 1','3.5 x 3.3m']);});
test('number beds with no matching labels makes no edit or AI call',async()=>{const h=harness(),before=h.pixels();await h.submit('number all beds');assert.equal(h.get().history.length,0);assert.equal(h.calls(),0);assert.deepEqual(h.pixels(),before);assert.match(h.el('status').textContent,/No bedroom labels/);});
test('explicit text and icon clearing removes selected labels and supports exact undo',async()=>{const h=harness(),before=h.pixels();h.el('aiedit').checked=true;h.select({x:280,y:270,w:180,h:80});await h.submit('remove all text and icons');assert.equal(h.calls(),0);assert.equal(h.get().labels.length,0);assert.equal(h.get().history.length,1);h.el('undo').onclick();assert.deepEqual(h.pixels(),before);assert.equal(h.get().labels.length,2);});
test('monochrome colourisation preserves dark line pixels, colours surfaces, undo restores original',()=>{const h=harness();h.c.qa.wall(100,100,150,150,'#bbb');h.c.qa.wall(100,100,150,5,'#000');const before=h.pixels(),dark=h.canvas.getContext('2d').getImageData(100,100,150,5).data;h.el('colour').onclick();const pixel=h.canvas.getContext('2d').getImageData(150,150,1,1).data;assert.notEqual(pixel[0],pixel[1]);assert.deepEqual(h.canvas.getContext('2d').getImageData(100,100,150,5).data,dark);h.el('undo').onclick();assert.deepEqual(h.pixels(),before);});
test('existing colour is kept exactly',()=>{const h=harness();h.c.qa.wall(100,100,150,150,'#88bb55');const before=h.pixels();h.el('colour').onclick();assert.deepEqual(h.pixels(),before);});
test('fan removal and label movement preserve text pixels and form one revision',async()=>{const h=harness();h.c.qa.seed([{id:'bed',text:'BEDROOM 2',x:300,y:200,w:150,h:25,fontSize:20,bg:'#fff'},{id:'size',text:'3.3 x 3.3',x:320,y:230,w:110,h:23,fontSize:18,bg:'#fff'}]);h.c.qa.wall(350,290,30,30,'#999');const before=h.pixels();h.setResponse({ok:true,json:async()=>({message:'',operations:[{type:'remove',labelId:'',text:'',rect:{x:340,y:280,w:60,h:60}}]})});await h.submit('remove the fan icons from the bedrooms and move the text labels down to be centred');assert.equal(h.get().history.length,1);assert(h.get().labels[0].y>200);assert.equal(h.get().labels[0].text,'BEDROOM 2');assert.equal(h.get().labels[1].text,'3.3 x 3.3');h.el('undo').onclick();assert.deepEqual(h.pixels(),before);});
