import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {createRequire} from 'node:module';
import * as hybrid from '../web/hybrid-contract.mjs';import * as fixtures from '../web/fixtures.mjs';import * as page from '../web/page-template.mjs';import * as actions from '../web/design-actions.mjs';import * as core from '../web/editor-core.mjs';
const require=createRequire(import.meta.url),{createCanvas,Image}=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules')+'/@napi-rs/canvas');
test('scaled pointer selection → submit BBQ → rename → undo; failed batch rolls back',async()=>{const els=new Map(),el=()=>({style:{},value:'',textContent:'',classList:{toggle(){}},replaceChildren(){},append(){},focus(){}});const canvas=createCanvas(1000,700);Object.assign(canvas,el(),{getBoundingClientRect:()=>({left:10,top:20,width:500,height:350}),setPointerCapture(){}});els.set('canvas',canvas);const document={getElementById:id=>{if(!els.has(id))els.set(id,el());return els.get(id)},createElement:t=>t==='canvas'?createCanvas(1,1):el(),querySelectorAll:()=>[]};let aiCalls=0;const context={...hybrid,...fixtures,...page,...actions,...core,document,Image,structuredClone,URL,AbortSignal,setTimeout,console,localStorage:{getItem:()=>''},fetch:async url=>{if(url==='/api/status')return {json:async()=>({aiReady:false})};aiCalls++;return {ok:false,json:async()=>({message:'AI not connected. Nothing was changed.'})}}};vm.createContext(context);let code=fs.readFileSync(new URL('../web/app.js',import.meta.url),'utf8').replace(/^(?:import[^\n]+\n)+/,'').replaceAll('import.meta.url',JSON.stringify(import.meta.url));code+=`\nglobalThis.state=()=>({labels,history,manual});globalThis.seed=()=>{img=makeCanvas(1000,700);let g=img.getContext('2d');g.fillStyle='white';g.fillRect(0,0,1000,700);g.fillStyle='black';g.font='20px Arial';g.fillText('FAMILY',400,300);sourceImage=img;labels=[{id:'family',text:'FAMILY',x:400,y:280,w:90,h:24,bg:'#fff'}];textRegions=[{x:400,y:280,w:90,h:24}];ready=true;original=false;render();};`;vm.runInContext(code,context);context.seed();const original=canvas.toBuffer('image/png');canvas.onpointerdown({clientX:60,clientY:70,pointerId:1});canvas.onpointerup({clientX:160,clientY:170,pointerId:1});assert.equal(context.state().manual.x,100);document.getElementById('instruction').value='add built in bbq in alfresco';await document.getElementById('revform').onsubmit({preventDefault(){}});assert.equal(context.state().history.length,1);assert.equal(aiCalls,0);assert.notDeepEqual(canvas.toBuffer('image/png'),original);assert.equal(context.state().manual,null);document.getElementById('instruction').value='replace family with living';await document.getElementById('revform').onsubmit({preventDefault(){}});assert.equal(context.state().labels[0].text,'living');assert.equal(context.state().labels[0].x,400);document.getElementById('undo').onclick();document.getElementById('undo').onclick();assert.deepEqual(canvas.toBuffer('image/png'),original);document.getElementById('instruction').value='rename family to living and add a car in driveway';await document.getElementById('revform').onsubmit({preventDefault(){}});assert.equal(aiCalls,1);assert.equal(context.state().labels[0].text,'FAMILY');assert.equal(context.state().history.length,0);assert.deepEqual(canvas.toBuffer('image/png'),original);assert.match(document.getElementById('status').textContent,/not connected/);
// New text in a selected blank area, then exact backward/forward navigation.
canvas.onpointerdown({clientX:60,clientY:220,pointerId:1});canvas.onpointerup({clientX:160,clientY:240,pointerId:1});
document.getElementById('instruction').value="Add 'site plan' in small black text";
await document.getElementById('revform').onsubmit({preventDefault(){}});
assert.equal(context.state().history.length,1);assert(context.state().labels.some(l=>l.text==='site plan'));
const withText=canvas.toBuffer('image/png');document.getElementById('undo').onclick();assert.deepEqual(canvas.toBuffer('image/png'),original);
document.getElementById('redo').onclick();assert.deepEqual(canvas.toBuffer('image/png'),withText);
// Selected measurement replacement works without an OCR label ID.
canvas.onpointerdown({clientX:60,clientY:220,pointerId:1});canvas.onpointerup({clientX:160,clientY:240,pointerId:1});
document.getElementById('instruction').value='change measurements to 8.0 x 4.0 m';
await document.getElementById('revform').onsubmit({preventDefault(){}});
assert(context.state().labels.some(l=>l.text==='8.0 x 4.0 m'));assert.equal(aiCalls,1);
const withMeasurement=canvas.toBuffer('image/png');document.getElementById('clearinstruction').onclick();assert.equal(document.getElementById('instruction').value,'');assert.deepEqual(canvas.toBuffer('image/png'),withMeasurement);
document.getElementById('undo').onclick();assert.deepEqual(canvas.toBuffer('image/png'),withText);document.getElementById('redo').onclick();assert.deepEqual(canvas.toBuffer('image/png'),withMeasurement);
document.getElementById('undo').onclick();
canvas.onpointerdown({clientX:60,clientY:260,pointerId:1});canvas.onpointerup({clientX:160,clientY:280,pointerId:1});
document.getElementById('instruction').value="Add 'garden' in small black text";await document.getElementById('revform').onsubmit({preventDefault(){}});
assert.equal(document.getElementById('redo').disabled,true);

context.seed();const label=context.state().labels[0];label.fontSize=20;label.color='#333333';const center=label.x+label.w/2,baseline=label.y+label.h/2;
context.applyLocal(label,'formal living');assert.equal(label.fontSize,20);assert.equal(label.color,'#333333');assert.equal(label.x+label.w/2,center);assert.equal(label.y+label.h/2,baseline);assert(label.w>90);
context.applyLocal(label,'lounge');assert.equal(label.fontSize,20);assert.equal(label.color,'#333333');assert.equal(label.x+label.w/2,center);assert.equal(label.y+label.h/2,baseline);
assert.equal(actions.parseAction("relabel as 'formal living'").to,'formal living');
});
